/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fid.tela;

import com.fid.hash.SenhaHash;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JEFFERSON
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblSem = new javax.swing.JLabel();
        btnEmcripit = new javax.swing.JToggleButton();
        lblSenha = new javax.swing.JLabel();
        lblSenha2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSenha3 = new javax.swing.JLabel();
        lblSenha4 = new javax.swing.JLabel();
        lblSenha5 = new javax.swing.JLabel();
        lblSenha6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Emcript Senha Hash ");

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSem.setText("Digite a senha");

        btnEmcripit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEmcripit.setText("Emcripit");
        btnEmcripit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmcripitActionPerformed(evt);
            }
        });

        lblSenha.setText("SENHA");

        lblSenha2.setText("SENHA");

        lblSenha3.setText("SENHA");

        lblSenha4.setText("SENHA");

        lblSenha5.setText("SENHA");

        lblSenha6.setText("SENHA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmcripit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(lblSem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSenha)
                                .addComponent(lblSenha2)
                                .addComponent(jLabel1)
                                .addComponent(lblSenha3)
                                .addComponent(lblSenha4)
                                .addComponent(lblSenha5)
                                .addComponent(lblSenha6)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSem))
                .addGap(18, 18, 18)
                .addComponent(btnEmcripit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addGap(18, 18, 18)
                .addComponent(lblSenha2)
                .addGap(18, 18, 18)
                .addComponent(lblSenha3)
                .addGap(18, 18, 18)
                .addComponent(lblSenha4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha6)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmcripitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmcripitActionPerformed
        //atributos Hash
        String md5 = "MD5";
            String sha1 = "SHA-1";
                String sha256 = "SHA-256";
                //Fim do atributo Hash
                    //Inicio da condição Try
                    try {
                        SenhaHash senha = new SenhaHash(); // extanciação da classe SenhaHash
                            String no = txtSenha.getText(); // capturando o que foi digitado
                            String novo = senha.Emcript(no); // inserindo o que foi digitado e chamando o metodo Emcript
                            //System.out.println(novo);
                        lblSenha.setText(novo); // mostrar o que foi retornado
            
                     byte[] nov1 = senha.gerarHash(no, md5); // inserindo o que foi digitado mais o atributo MD5 e chamando o metodo gerarHash
                byte[] nov2 = senha.gerarHash(no, sha1); // inserindo o que foi digitado mais o atributo sha-1 e chamando o metodo gerarHash
            byte[] nov3 = senha.gerarHash(no, sha256); // inserindo o que foi digitado mais o atributo sha-256 e chamando o metodo gerarHash
            
        byte[] nov4 = senha.novoEmcript(novo, md5); // inserindo o que foi digitado mais o atributo MD5 e chamando o metodo novoEmcript
        
    byte[] nov5 = senha.processaSolicitacao(novo, md5); // inserindo o que foi digitado mais o atributo MD5 e chamando o metodo processaSolicitacao
String nov6 = senha.retornoString(nov5); //retornando string do metodo processaSolicitacao
            
System.out.println(nov1); //Imprimindo no shell o nov1
System.out.println(nov2);  //Imprimindo no shell o nov2
    System.out.println(nov3);  //Imprimindo no shell o nov3
        System.out.println(nov4);  //Imprimindo no shell o nov4
            System.out.println(nov5);  //Imprimindo no shell o nov5
            
                String a1 = new String(nov1); // convertendo o retorno do nov1 em texto
                    String a2 = new String(nov2); // convertendo o retorno do nov2 em texto
                        String a3 = new String(nov3); // convertendo o retorno do nov3 em texto
                            String a4 = new String(nov4); // convertendo o retorno do nov4 em texto
                                String a5 = new String(nov6); // convertendo o retorno do nov5 em texto
            
                                    txtNome.setText(a5); //Mostrando o resultado do a5 no campo txtNome (JTextField)
                                    lblSenha2.setText(a1); //Mostrando o resultado do a1 no campo lblSenha2 (JLabel)
                                lblSenha3.setText(a2); //Mostrando o resultado do a1 no campo lblSenha3 (JLabel)
                            lblSenha4.setText(a3); //Mostrando o resultado do a1 no campo lblSenha4 (JLabel)
                        lblSenha5.setText(a4);//Mostrando o resultado do a1 no campo lblSenha5 (JLabel)
                    lblSenha6.setText(a5); //Mostrando o resultado do a1 no campo lblSenha5 (JLabel)
            
                } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex); // Não sei o que essa porra faz
        } catch (UnsupportedEncodingException ex) {
    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex); // muito menos essa
}
        
    }//GEN-LAST:event_btnEmcripitActionPerformed
    //fim da condição Try
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEmcripit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha2;
    private javax.swing.JLabel lblSenha3;
    private javax.swing.JLabel lblSenha4;
    private javax.swing.JLabel lblSenha5;
    private javax.swing.JLabel lblSenha6;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
